apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: kubedb-mongodb-ops-request-failed
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        description: Check the conditions of the MongoDBOpsRequest.
        target: OpsRequest
    - type: CheckEvents
      args:
        description: Describe the MongoDBOpsRequest and check the events.
        target: OpsRequest
    - type: CheckLogs
      args:
        description: Check the KubeDB ops manager operator pod logs
        target: OpsManagerOperatorPod