apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: kubedb-mongodb-phase-not-ready
spec:
  diagnosticChecks:
    - type: InspectConditions
      args:
        description: Check the reasons for the Conditions that are false in the MongoDB CR.
        target: DatabaseInstance
    - type: InspectLogs
      args:
        description: Check mongodb pod logs
        target: DatabasePod
    - type: InspectLogs
      args:
        description: Check KubeDB provisioner logs
        target: KubeDBProvisionerPod