apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: kubedb-mongodb-phase-critical
spec:
  variables:
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
    - name: k8sResource
      valueFrom:
        alertPathRef:
          path: .labels.k8s_resource
  diagnosticChecks:
    - type: CheckStatusAnomalies
      args:
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
        fields:
          - path: status.conditions[?status == 'False']
            matchCriteria:
              operator: NotEmpty
    - type: CheckEvents
      args:
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
  remedyActions:
    - type: Restart
      args:
        description: Try restarting the pods
        target: DatabasePod
