apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: kubedb-mongodb-ops-request-status-progressing-to-long
spec:
  diagnosticChecks:
    - type: InspectLogs
      args:
        description: Check the KubeDB ops manager operator pod logs
        target: OpsManagerOperatorPod