apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: kubedb-mongodb-ops-request-status-progressing-to-long
spec:
  diagnosticChecks:
    - type: CheckLogs
      args:
        - name: appNamespace
          valueFrom:
            path: .labels.app_namespace
        - name: selector
          valueFrom:
            template: app.kubernetes.io/component=database,app.kubernetes.io/name={{.labels.k8s_resource}}.{{.labels.k8s_group}},app.kubernetes.io/managed-by={{.labels.k8s_group}},app.kubernetes.io/instance:={{.labels.app }}