apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: kubedb-mongodb-ops-request-failed
spec:
  diagnosticChecks:
    - type: InspectPodConditions
      args:
        description: Describe the MongoDBOpsRequest and check the conditions.
    - type: InspectEvents
      args:
        description: Describe the MongoDBOpsRequest and check the events.
    - type: InspectLogs
      args:
        description: Check the KubeDB ops manager operator pod logs
        for: DatabaseLogs
  remedyActions: