apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: kubedb-mongodb-ops-request-failed
spec:
  variables:
    - name: namespace
      valueFrom:
        alertPathRef:
          path: .labels.namespace
    - name: mongoDBOpsRequest
      valueFrom:
        alertPathRef:
          path: .labels.mongodbopsrequest
  diagnosticChecks:
    - type: CheckStatusAnomalies
      args:
        resourceGroup: ops.kubedb.com
        resourceKind: MongoDBOpsRequest
        resourceName: ${mongoDBOpsRequest}
        resourceNamespace: ${namespace}
        anomalyRules:
          resourceVersions:
            - name: v1alpha1
              rules:
                - conditionExpr: "status.conditions.exists(c, c.status=='False')"
                  outputExpr: "status.conditions.filter(c, c.status=='False')"
    - type: CheckEvents
      args:
        maxEventLimit: 5
        resourceGroup: ops.kubedb.com
        resourceKind: MongoDBOpsRequest
        resourceName: ${mongoDBOpsRequest}
        resourceNamespace: ${namespace}
    - type: CheckLogs
      args:
        tailLines: 50
        labelSelector: app.kubernetes.io/name=kubedb-ops-manager
        containers: operator
