apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: kubedb-mongodb-ops-request-failed
spec:
  variables:
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
  diagnosticChecks:
    - type: CheckStatusAnomalies
      args:
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
        anomalyRules:
          - path: "status.conditions.transformMap(name, c, c.status=='False', c)"
            matchCriteria:
              operator: NotEmpty
    - type: CheckEvents
      args:
        maxEventLimit: 10
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
    - type: CheckLogs
      args:
        tailLines: 50
        labelSelector: app.kubernetes.io/name=kubedb-ops-manager
        containers: operator
