apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: kubedb-mongodb-phase-not-ready
spec:
  variables:
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
    - name: k8sResource
      valueFrom:
        alertPathRef:
          path: .labels.k8s_resource
  diagnosticChecks:
    - type: CheckConditions
      args:
        - name: appGroup
          value: ${k8sGroup}
        - name: appKind
          value: ${k8sKind}
        - name: appName
          value: ${app}
        - name: appNamespace
          value: ${appNamespace}
    - type: CheckLogs
      args:
        - name: appNamespace
          value: ${appNamespace}
        - name: selector
          value: app.kubernetes.io/component=database,app.kubernetes.io/name=${k8sResource}.${k8sGroup},app.kubernetes.io/managed-by=${k8sGroup},app.kubernetes.io/instance:=${app}
        - name: containers
          value: "init,mongodb"