apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: kubedb-mongodb-phase-critical
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        - name: appGroup
          valueFrom:
            path: .labels.k8s_group
        - name: appKind
          valueFrom:
            path: .labels.k8s_kind
        - name: appName
          valueFrom:
            path: .labels.app
        - name: appNamespace
          valueFrom:
            path: .labels.app_namespace
    - type: CheckEvents
      args:
        - name: appGroup
          valueFrom:
            path: .labels.k8s_group
        - name: appKind
          valueFrom:
            path: .labels.k8s_kind
        - name: appName
          valueFrom:
            path: .labels.app
        - name: appNamespace
          valueFrom:
            path: .labels.app_namespace
  remedyActions:
    - type: Restart
      args:
        description: Try restarting the pods
        target: DatabasePod