apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: kubedb-mongodb-phase-critical
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        description: Check the reasons for the Conditions that are false in the MongoDB CR.
        target: DatabaseInstance
    - type: CheckEvents
      args:
        description: Describe the pods that are not Ready and check their events.
        target: DatabasePod
  remedyActions:
    - type: Restart
      args:
        description: Try restarting the pods
        target: DatabasePod