apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-high-latency
spec:
  variables:
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
    - name: k8sResource
      valueFrom:
        alertPathRef:
          path: .labels.k8s_resource
  diagnosticChecks:
    - type: CheckLogs
      args:
        - name: appNamespace
          value: ${appNamespace}
        - name: labelSelector
          value: app.kubernetes.io/component=database,app.kubernetes.io/name=${k8sResource}.${k8sGroup},app.kubernetes.io/managed-by=${k8sGroup},app.kubernetes.io/instance:=${app}
        - name: containers
          value: "init,mongodb"
    - type: CheckSlowQueries
      args:
        description: Check for slow queries using db.currentOp() command
    - type: CheckNetworkAndDiskPerformance
      args:
        description: Check for network and disk performance