apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-replication-lag
spec:
  variables:
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: k8sResource
      valueFrom:
        alertPathRef:
          path: .labels.k8s_resource
    - name: podName
      valueFrom:
        alertPathRef:
          path: .labels.pod
  diagnosticChecks:
    - type: CheckReplicationLagData
      args:
        replicationLagThreshold: 10
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
    - type: CheckSlowQueries
      args:
        maxQueryDuration: 2h
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
    - type: CheckNetworkPerformance
      args:
        trafficThreshold: 500000
        requestThreshold: 2500
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
        podName: ${podName}
    - type: CheckDiskPerformance
      args:
        cacheLimit: 2684354560
        dirtyBytesThreshold: 100000000
        logWriteThreshold: 50000000
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
        podName: ${podName}
