apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-cursors-timeouts
spec:
  variables:
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
    - name: k8sResource
      valueFrom:
        alertPathRef:
          path: .labels.k8s_resource
    - name: podName
      valueFrom:
        alertPathRef:
          path: .labels.pod
  diagnosticChecks:
    - type: CheckLogs
      args:
        tailLines: 50
        resourceNamespace: ${appNamespace}
        labelSelector: >-
          app.kubernetes.io/component=database,
          app.kubernetes.io/name=${k8sResource}.${k8sGroup},
          app.kubernetes.io/managed-by=${k8sGroup},
          app.kubernetes.io/instance=${app}
        containers: mongodb
    - type: CheckSlowQueries
      args:
        maxQueryDuration: 2h
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
    - type: CheckNetworkPerformance
      args:
        trafficThreshold: 500000
        requestThreshold: 2500
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
        podName: ${podName}
    - type: CheckDiskPerformance
      args:
        cacheLimit: 2684354560
        dirtyBytesThreshold: 100000000
        logWriteThreshold: 50000000
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
        podName: ${podName}