apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-kube-stash-no-backup-session-for-too-long
spec:
  variables:
    - name: namespace
      valueFrom:
        alertPathRef:
          path: .labels.namespace
    - name: backup_invoker_kind
      valueFrom:
        alertPathRef:
          path: .labels.backup_invoker_kind
    - name: backup_invoker_name
      valueFrom:
        alertPathRef:
          path: .labels.backup_invoker_name
  diagnosticChecks:
    - type: CheckStatusAnomalies
      args:
        resourceGroup: core.kubestash.com
        resourceKind: ${backup_invoker_kind}
        resourceName: ${backup_invoker_name}
        resourceNamespace: ${namespace}
        anomalyRules:
          resourceVersions:
            - name: v1
              rules:
                - conditionExpr: "spec.paused==true"
                  outputExpr: "spec.paused"
