apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-kubestash-restore-session-period-too-long
spec:
  variables:
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
    - name: k8sResource
      valueFrom:
        alertPathRef:
          path: .labels.k8s_resource
  diagnosticChecks:
    - type: CheckStatusAnomalies
      args:
        appGroup: ${k8sGroup}
        appKind: ${k8sKind}
        appName: ${app}
        appNamespace: ${appNamespace}
        fields:
          - path: status.conditions[?status == 'False']
            matchCriteria:
              operator: NotEmpty
    - type: CheckRepositoryIntegrity
      args:
        description: Check if the INTEGRITY of Repository is true