apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-kubestash-restore-session-failed
spec:
  variables:
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
    - name: restoresession
      valueFrom:
        alertPathRef:
          path: .labels.restoresession
    - name: namespace
      valueFrom:
        alertPathRef:
          path: .labels.namespace
  diagnosticChecks:
    - type: CheckStatusAnomalies
      args:
        resourceGroup: core.kubestash.com
        resourceKind: RestoreSession
        resourceName: ${restoresession}
        resourceNamespace: ${namespace}
        fields:
          - path: status.components.* | [?phase == 'Failed']
            matchCriteria:
              operator: NotEmpty
    - type: CheckEvents
      args:
        resourceGroup: core.kubestash.com
        resourceKind: RestoreSession
        resourceName: ${restoresession}
        resourceNamespace: ${namespace}
    - type: CheckLogs
      args:
        resourceNamespace: ${namespace}
        selector: >-
          app.kubernetes.io/component=kubestash-restore,
          app.kubernetes.io/managed-by=kubestash.com,
          kubestash.com/invoker-name=${restoresession},
          kubestash.com/invoker-namespace=${namespace}
          
