apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-kubestash-restore-session-period-too-long
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        - name: appGroup
          valueFrom:
            path: .labels.k8s_group
        - name: appKind
          valueFrom:
            path: .labels.k8s_kind
        - name: appName
          valueFrom:
            path: .labels.app
        - name: appNamespace
          valueFrom:
            path: .labels.app_namespace
    - type: CheckRepositoryIntegrity
      args:
        description: Check if the INTEGRITY of Repository is true