apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-kubestash-backup-session-period-too-long
spec:
  variables:
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: namespace
      valueFrom:
        alertPathRef:
          path: .labels.namespace
    - name: backupsession
      valueFrom:
        alertPathRef:
          path: .labels.backupsession
    - name: startsAt
      valueFrom:
        alertPathRef:
          path: .startsAt
  diagnosticChecks:
    - type: CheckLogs
      args:
        alertStartTime: ${startsAt}
        resourceNamespace: ${namespace}
        labelSelector: >-
          app.kubernetes.io/component=kubestash-backup, app.kubernetes.io/managed-by=kubestash.com, kubestash.com/invoker-name=${backupsession}, kubestash.com/invoker-namespace=${namespace}
