apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-kube-stash-backup-session-failed
spec:
  variables:
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: namespace
      valueFrom:
        alertPathRef:
          path: .labels.namespace
    - name: backupsession
      valueFrom:
        alertPathRef:
          path: .labels.backupsession
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
  diagnosticChecks:
    - type: CheckStatusAnomalies
      args:
        resourceGroup: core.kubestash.com
        resourceKind: BackupSession
        resourceName: ${backupsession}
        resourceNamespace: ${namespace}
        anomalyRules:
          - conditionExpr: "status.conditions.exists(c, c.status=='False')"
            outputExpr: "status.conditions.filter(c, c.status=='False')"
          - conditionExpr: "status.retentionpolicy.exists(rp, rp.phase=='FailedToApply')"
            outputExpr: "status.retentionPolicy.filter(rp, rp.phase=='FailedToApply')"
    - type: CheckLogs
      args:
        resourceNamespace: ${appNamespace}
        labelSelector: >-
          app.kubernetes.io/component=kubestash-backup,
          app.kubernetes.io/managed-by=kubestash.com,
          kubestash.com/invoker-name=${backupsession},
          kubestash.com/invoker-namespace=${namespace}
