apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-kube-stash-restore-session-period-too-long
spec:
  diagnosticChecks:
    - type: InspectConditions
      args:
        description: Check the MongoDB CRs status
        target: DatabaseInstance
    - type: InspectRepositoryIntegrity
      args:
        description: Check if the INTEGRITY of Repository is true