apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-kubestash-backup-session-period-too-long
spec:
  diagnosticChecks:
    - type: InspectConditions
      args:
        description: Check the MongoDB CRs status
        target: DatabaseInstance
    - type: InspectLogs
      args:
        description: Check the Restore Job logs
        target: RestorePod