apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-kubestash-restore-session-failed
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        description: Check the conditions of the RestoreSession
        target: RestoreSession
    - type: CheckEvents
      args:
        description: Check the events of the RestoreSession
        target: RestoreSession
    - type: CheckLogs
      args:
        description: Check the Restore Job logs
        target: RestorePod
    - type: CheckLogs
      args:
        description: Check the KubeStash operator log
        target: KubeStashOperatorPod
    - type: CheckRepositoryIntegrity
      args:
        description: Check if the INTEGRITY of Repository is true