apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-recurrent-cursor-timeout
spec:
  diagnosticChecks:
    - type: CheckLogs
      args:
        description: Check database pod logs
        for: DatabasePod
  remedyActions:
    - type: CheckSlowQueries
      args:
        description: Check for slow queries using db.currentOp() command
    - type: CheckNetworkAndDiskPerformance
      args:
        description: Check for network and disk performance