apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-down
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        description: Check the reasons for the Conditions that are false in the MongoDB CR.
        target: DatabaseInstance
    - type: CheckLogs
      args:
        description: Check database pod logs
        target: DatabasePod
  remedyActions:
    - type: Restart
      args:
        description: Try restarting the pods
        target: DatabasePod