apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-virtual-memory-usage
spec:
  diagnosticChecks:
  remedyActions:
    - type: IncreaseMemory
      args:
        description: Increase storage and/or memory using VerticalScaling OpsRequest and VolumeExpansion OpsRequest
