apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-down
spec:
  diagnosticChecks:
    - type: InspectConditions
      args:
        description: Describe the MongoDB CR, check the reason from conditions.
    - type: InspectLogs
      args:
        description: Check database pod logs
        for: DatabaseLogs
  remedyActions:
    - type: RestartPod
      args:
        description: Try restarting the pods