apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-high-ticket-utilization
spec:
  diagnosticChecks:
    - type: CheckLogs
      args:
        - name: appNamespace
          valueFrom:
            path: .labels.app_namespace
        - name: labelSelector
          valueFrom:
            template: "app.kubernetes.io/name={{.labels.k8s_resource}}.{{.labels.k8s_group}},app.kubernetes.io/component=database,app.kubernetes.io/managed-by={{.labels.k8s_group}},app.kubernetes.io/instance:={{ .labels.app }}"
  remedyActions:
    - type: CheckSlowQueries
      args:
        description: Check for slow queries using db.currentOp() command
    - type: CheckNetworkAndDiskPerformance
      args:
        description: Check for network and disk performance