apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-kubestash-no-backup-session-for-too-long
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        description: Check the conditions of the BackupConfiguration.
        target: BackupConfiguration
    - type: CheckEvents
      args:
        description: Check the events of the BackupConfiguration
        target: BackupConfiguration
    - type: CheckLogs
      args:
        description: Check the KubeStash operator log
        target: KubeStashOperatorPod
    - type: CheckBackupTargetStatus
    - type: CheckRepositoryStatus
    - type: CheckBackendStatus
    - type: CheckBackupDependencyStatus