apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-stash-backup-session-failed
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        description: Check the conditions of the BackupSession
        target: BackupSession
    - type: CheckEvents
      args:
        description: Check the events of the BackupSession
        target: BackupSession
    - type: CheckLogs
      args:
        description: Check the Backup Job logs
        target: BackupPod
    - type: CheckLogs
      args:
        description: Check the KubeStash operator log
        target: KubeStashOperatorPod
    - type: CheckRepositoryIntegrity
      args:
        description: Check if the INTEGRITY of Repository is true