apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-kubestash-restore-session-failed
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        - name: appGroup
          valueFrom:
            path: .labels.k8s_group
        - name: appKind
          valueFrom:
            path: .labels.k8s_kind
        - name: appName
          valueFrom:
            path: .labels.app
        - name: appNamespace
          valueFrom:
            path: .labels.app_namespace
    - type: CheckEvents
      args:
        description: Check the events of the RestoreSession
        target: RestoreSession
    - type: CheckLogs
      args:
        - name: appNamespace
          valueFrom:
            path: .labels.app_namespace
        - name: labelSelector
          valueFrom:
            template: "app.kubernetes.io/name={{.labels.k8s_resource}}.{{.labels.k8s_group}},app.kubernetes.io/component=database,app.kubernetes.io/managed-by={{.labels.k8s_group}},app.kubernetes.io/instance:={{ .labels.app }}"
    - type: CheckLogs
      args:
        - name: appNamespace
          valueFrom:
            path: .labels.app_namespace
        - name: labelSelector
          valueFrom:
            template: "app.kubernetes.io/name={{.labels.k8s_resource}}.{{.labels.k8s_group}},app.kubernetes.io/component=database,app.kubernetes.io/managed-by={{.labels.k8s_group}},app.kubernetes.io/instance:={{ .labels.app }}"
    - type: CheckRepositoryIntegrity
      args:
        description: Check if the INTEGRITY of Repository is true