apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-kubestash-restore-session-period-too-long
spec:
  diagnosticChecks:
    - type: CheckConditions
      args:
        description: Check the MongoDB CRs status
        target: DatabaseInstance
    - type: CheckRepositoryIntegrity
      args:
        description: Check if the INTEGRITY of Repository is true