apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-kube-stash-no-backup-session-for-too-long
spec:
  diagnosticChecks:
    - type: InspectConditions
      args:
        description: Describe the BackupConfiguration
        target: BackupConfiguration
    - type: InspectEvents
      args:
        description: Check the events of the BackupConfiguration
    - type: InspectLogs
      args:
        description: Check the KubeStash operator log
        target: OperatorLog
  remedyActions: