apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-high-latency
spec:
  diagnosticChecks:
    - type: InspectLogs
      args:
        description: Check database pod logs
        target: DatabasePod
  remedyActions:
    - type: CheckSlowQueries
      args:
        description: Check for slow queries using db.currentOp() command
    - type: CheckNetworkAndDiskPerformance
      args:
        description: Check for network and disk performance