apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mongodb-down
spec:
  diagnosticChecks:
    - type: InspectConditions
      args:
        description: Describe the MongoDB CR, check the reason from conditions and try restarting the pods
    - type: InspectDatabaseLogs
      args:
        description: Check database pod logs
  remedyActions:
    - type: RestartPod
      args:
        description: try restarting the pods
