apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-kubestash-restore-session-period-too-long
spec:
  variables:
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
    - name: k8sResource
      valueFrom:
        alertPathRef:
          path: .labels.k8s_resource
  diagnosticChecks:
    - type: CheckConditions
      args:
        - name: appGroup
          value: ${k8sGroup}
        - name: appKind
          value: ${k8sKind}
        - name: appName
          value: ${app}
        - name: appNamespace
          value: ${appNamespace}
    - type: CheckRepositoryIntegrity
      args:
        description: Check if the INTEGRITY of Repository is true