apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-kubestash-restore-session-failed
spec:
  variables:
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: restoresession
      valueFrom:
        alertPathRef:
          path: .labels.restoresession
    - name: namespace
      valueFrom:
        alertPathRef:
          path: .labels.namespace
    - name: startsAt
      valueFrom:
        alertPathRef:
          path: .startsAt
  diagnosticChecks:
    - type: CheckStatusAnomalies
      args:
        resourceGroup: core.kubestash.com
        resourceKind: RestoreSession
        resourceName: ${restoresession}
        resourceNamespace: ${namespace}
        anomalyRules:
          - path: status.conditions[?status == 'False']
            matchCriteria:
              operator: NotEmpty
          - path: status.components.* | [?phase == 'Failed']
            matchCriteria:
              operator: NotEmpty
    - type: CheckEvents
      args:
        alertStartTime: ${startsAt}
        maxEventLimit: 10
        lookbackDuration: 1000000
        resourceGroup: core.kubestash.com
        resourceKind: RestoreSession
        resourceName: ${restoresession}
        resourceNamespace: ${namespace}
    - type: CheckLogs
      args:
        alertStartTime: ${startsAt}
        lookbackDuration: 1000000
        resourceNamespace: ${namespace}
        tailLines: 30
        labelSelector: >-
          app.kubernetes.io/component=kubestash-restore, app.kubernetes.io/managed-by=kubestash.com, kubestash.com/invoker-name=${restoresession}, kubestash.com/invoker-namespace=${namespace}
