apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mongodb-kubestash-restore-session-period-too-long
spec:
  variables:
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: namespace
      valueFrom:
        alertPathRef:
          path: .labels.namespace
    - name: restoresession
      valueFrom:
        alertPathRef:
          path: .labels.restoresession
  diagnosticChecks:
    - type: CheckLogs
      args:
        resourceNamespace: ${appNamespace}
        labelSelector: >-
          app.kubernetes.io/component=kubestash-restore,
          app.kubernetes.io/managed-by=kubestash.com,
          kubestash.com/invoker-name=${restoresession},
          kubestash.com/invoker-namespace=${namespace}