apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: backup-session-failed
spec:
  diagnosticChecks:
    - type: InspectConditions
      args:
        description: Describe the BackupSession
        target: BackupSession
    - type: InspectEvents
      args:
        description: Check the events of the BackupSession
    - type: InspectLogs
      args:
        description: View the Backup Job/Sidecar log
        target: SidecarLog
    - type: InspectLogs
      args:
        description: Check the KubeStash operator log
        target: KubeStashOperatorPod
    - type: InspectRepositoryIntegrity
      args:
        description: Check if the INTEGRITY of Repository is true
  remedyActions: