apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mysql-inno-db-log-waits
spec:
  variables:
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
    - name: k8sGroup
      valueFrom:
        alertPathRef:
          path: .labels.k8s_group
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: podName
      valueFrom:
        alertPathRef:
          path: .labels.pod
  diagnosticChecks:
    - type: CheckInnoDBLogWaitData
      args:
        resourceGroup: ${k8sGroup}
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
        podName: ${podName}
  remedyActions:
    - type: IncreaseLogBufferSize
      args:
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
        podName: ${podName}