apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  name: mysql-too-many-connections
spec:
  variables:
    - name: k8sKind
      valueFrom:
        alertPathRef:
          path: .labels.k8s_kind
    - name: app
      valueFrom:
        alertPathRef:
          path: .labels.app
    - name: appNamespace
      valueFrom:
        alertPathRef:
          path: .labels.app_namespace
  remedyActions:
    - type: IncreaseMaxConnections
      args:
        resourceKind: ${k8sKind}
        resourceName: ${app}
        resourceNamespace: ${appNamespace}
