apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: mysql-restarted
spec:
  diagnosticChecks:
    - type: InspectConditions
      args:
        description: Check if MySQL CR is in Ready status
  remedyActions: