apiVersion: monitoring.appscode.com/v1alpha1
kind: Runbook
metadata:
  namespace: monitoring
  name: postgresql-restarted
spec:
  diagnosticChecks:
    - type: InspectConditions
      args:
        description: Check if Postgres CR is in Ready status
        target: DatabaseInstance
  remedyActions: